name: Deploy

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Deploy via sFTP
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
          ARGS: '-avz --delete'
          SOURCE: './'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_PATH }}
          EXCLUDE: '.*, eslint.config.mjs, package.json, package-lock.json, README.md, node_modules/*, photos/*' # don't upload these
