name: Deploy

on:
  push:
    branches: ['main']

  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: easingthemes/ssh-deploy@main
        with:
          ssh-private-key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          args: '-avz --delete --exclude=/photos' # don't delete /photos on server
          source: './'
          remote-host: ${{ secrets.REMOTE_HOST }}
          remote-user: ${{ secrets.REMOTE_USER }}
          target: ${{ secrets.REMOTE_PATH }}
          exclude: 'node_modules/*' # don't upload node_modules
